domiotek/fintrack

backend/.gitattributes
backend/.gitignore
backend/.mvn/wrapper/maven-wrapper.properties
backend/mvnw
backend/mvnw.cmd
backend/pom.xml
backend/src/main/java/com/example/fintrack/FintrackApplication.java
backend/src/main/resources/application.properties
backend/src/test/java/com/example/fintrack/FintrackApplicationTests.java

backend init

---

backend/Dockerfile
backend/pom.xml
docker-compose.yml
front/.dockerignore
front/Dockerfile

Full docker compose setup with postgres database, angular app and java spring api

Add docker compose setup

---

front/package-lock.json
front/package.json
front/src/app/styles/_typography.scss
front/src/app/styles/_variables.scss
front/src/index.html
front/src/styles.scss

Feat:
- add angular material
- add basic variables and setup

feat: add angular material and scss variables and basic setup

---

front/src/app/app.routes.ts
front/src/app/core/guards/auth.guard.spec.ts
front/src/app/core/guards/auth.guard.ts

Feats:
- ready canActivate auth guard

feat: auth guard

---

front/src/app/app.config.ts
front/src/app/core/models/auth/config-response.model.ts
front/src/app/core/models/currency/currency.model.ts
front/src/app/core/services/auth/auth.service.ts
front/src/app/core/services/config/config.service.spec.ts
front/src/app/core/services/config/config.service.ts

Feats:
- app initializer
- config service with mocked functions

feat: app initializer & mocked get config

---

backend/src/main/java/com/example/fintrack/config/RedisConfig.java
docker-compose.yml

Added host name for docker build

Redis host name changed

---

backend/src/main/java/com/example/fintrack/config/RedisConfiguration.java
backend/src/main/java/com/example/fintrack/currency/CurrencyController.java
backend/src/main/java/com/example/fintrack/currency/CurrencyDto.java
backend/src/main/java/com/example/fintrack/currency/CurrencyService.java
backend/src/main/java/com/example/fintrack/currency/Rate.java
backend/src/main/java/com/example/fintrack/security/SecurityFilterChainConfiguration.java
backend/src/main/java/com/example/fintrack/user/UserController.java

Currencies endpoint

---

front/src/app/app.routes.ts
front/src/app/core/components/header-bar/header-bar.component.html
front/src/app/core/components/header-bar/header-bar.component.scss
front/src/app/core/components/header-bar/header-bar.component.spec.ts
front/src/app/core/components/header-bar/header-bar.component.ts
front/src/app/core/components/main-layout/main-layout.component.html
front/src/app/core/components/main-layout/main-layout.component.spec.ts
front/src/app/core/components/main-layout/main-layout.component.ts
front/src/app/core/components/side-nav/nav-item/nav-item.component.html
front/src/app/core/components/side-nav/nav-item/nav-item.component.scss
front/src/app/core/components/side-nav/nav-item/nav-item.component.spec.ts
front/src/app/core/components/side-nav/nav-item/nav-item.component.ts
front/src/app/core/components/side-nav/side-nav.component.html
front/src/app/core/components/side-nav/side-nav.component.scss
front/src/app/core/components/side-nav/side-nav.component.spec.ts
front/src/app/core/components/side-nav/side-nav.component.ts
front/src/app/core/constants/navigation/headers.ts
front/src/app/core/constants/navigation/route-titles.ts
front/src/app/core/models/navigation/nav-item.model.ts
front/src/app/core/store/app-state.store.ts
front/src/app/styles/_typography.scss
front/src/styles.scss

Feats:
- sidenav
- main layout
- navigation with main layout for authenticated pages

feat: sidenav & mainlayout

---

front/src/app/core/components/side-nav/side-nav.component.html
front/src/app/core/components/side-nav/side-nav.component.scss

Fix:
- margin in main content after sidenav state change
- text-overflow correction in sidenav title

fix: navbar content margin and text-overflow

---

front/src/app/core/components/side-nav/side-nav.component.html
front/src/app/core/components/side-nav/side-nav.component.ts

Fix:
- content margin on mobile in navbar correction

fix: navbar margin on mobile

---

backend/pom.xml
backend/src/main/java/com/example/fintrack/authentication/AuthenticationController.java
backend/src/main/java/com/example/fintrack/authentication/Password.java
backend/src/main/java/com/example/fintrack/authentication/PasswordConstraintValidator.java
backend/src/main/java/com/example/fintrack/authentication/dto/LoginRequestDto.java
backend/src/main/java/com/example/fintrack/authentication/dto/RegisterRequestDto.java
backend/src/main/java/com/example/fintrack/constraints/FieldsValueMatch.java
backend/src/main/java/com/example/fintrack/constraints/FieldsValueMatchConstraintValidator.java
backend/src/main/java/com/example/fintrack/exception/GlobalExceptionHandler.java
backend/src/main/resources/application.yaml
backend/src/test/resources/application.yaml

Added constraints for password and field matching

Added constraints for password and field matching

---

backend/src/main/java/com/example/fintrack/authentication/AuthenticationService.java
backend/src/main/java/com/example/fintrack/bill/AddBillEventDto.java
backend/src/main/java/com/example/fintrack/bill/BillService.java
backend/src/main/java/com/example/fintrack/event/EventController.java
backend/src/main/java/com/example/fintrack/event/EventService.java
backend/src/main/java/com/example/fintrack/event/dto/AddEventDto.java
backend/src/main/java/com/example/fintrack/exception/BusinessErrorCodes.java
backend/src/main/java/com/example/fintrack/user/UserService.java

Added endpoints for adding event and bill to event

Event post endpoints

---

backend/src/main/java/com/example/fintrack/DataInitializer.java
backend/src/main/java/com/example/fintrack/FintrackApplication.java
backend/src/main/java/com/example/fintrack/authentication/AuthenticationService.java
backend/src/main/java/com/example/fintrack/exception/BusinessErrorCodes.java
backend/src/main/java/com/example/fintrack/rate/RateService.java
backend/src/main/java/com/example/fintrack/rate/RatesDto.java

Scheduled rates update

---

backend/src/main/java/com/example/fintrack/FintrackApplication.java
backend/src/main/java/com/example/fintrack/bill/BillService.java
backend/src/main/java/com/example/fintrack/category/CategoryController.java
backend/src/main/java/com/example/fintrack/category/CategoryService.java
backend/src/main/java/com/example/fintrack/category/dto/LimitDto.java
backend/src/main/java/com/example/fintrack/config/ApplicationConfiguration.java
backend/src/main/java/com/example/fintrack/event/EventController.java
backend/src/main/java/com/example/fintrack/event/EventService.java

Pagination configuration updated
Added global page serialization
Added pagination default values

Pagination update

---

backend/src/main/java/com/example/fintrack/event/EventController.java
backend/src/main/java/com/example/fintrack/event/EventMapper.java
backend/src/main/java/com/example/fintrack/event/EventService.java
backend/src/main/java/com/example/fintrack/event/dto/SettlementCurrencyDto.java
backend/src/main/java/com/example/fintrack/event/dto/SettlementDto.java
backend/src/main/java/com/example/fintrack/event/dto/SettlementUserDto.java

Added endpoint for calculating settlements

Calculating settlements

---

backend/src/main/java/com/example/fintrack/currency/CurrencyConverter.java
backend/src/main/java/com/example/fintrack/exception/BusinessErrorCodes.java

Added converter backup currency

Added converter backup currency

---

backend/src/main/java/com/example/fintrack/bill/BillService.java
backend/src/main/java/com/example/fintrack/category/CategoryService.java
backend/src/main/java/com/example/fintrack/exception/BusinessErrorCodes.java
backend/src/main/java/com/example/fintrack/friend/FriendService.java
backend/src/main/java/com/example/fintrack/user/UserMapper.java
backend/src/main/java/com/example/fintrack/user/dto/UserProfileDto.java

Fixed problems with hibernate session
Added errors for friends
Added user id in profile info

Fixed problems with hibernate session and added errors for friends

---

backend/src/main/java/com/example/fintrack/chat/ChatController.java
backend/src/main/java/com/example/fintrack/chat/ChatService.java
backend/src/main/java/com/example/fintrack/chat/dto/ChatStateDto.java
backend/src/main/java/com/example/fintrack/lastreadmessage/LastReadMessageMapper.java
backend/src/main/java/com/example/fintrack/lastreadmessage/LastReadMessageRepository.java
backend/src/main/java/com/example/fintrack/lastreadmessage/dto/LastReadMessageDto.java

Added last read messages to chat state

Chat state

---

backend/src/main/java/com/example/fintrack/DataInitializer.java

Fixed mock data

---

backend/src/main/java/com/example/fintrack/chat/ChatConfiguration.java

Websocket cors fix

---

backend/src/main/java/com/example/fintrack/chat/ChatMapper.java
backend/src/main/java/com/example/fintrack/chat/ChatService.java
backend/src/main/java/com/example/fintrack/chat/dto/PrivateChatFriendDto.java

Last seen at field

---

backend/src/main/java/com/example/fintrack/category/CategoryMapper.java
backend/src/main/java/com/example/fintrack/category/dto/CategoryDto.java

Category fix

---

front/src/app/core/components/side-nav/side-nav.component.ts

feats:
- close sidenav on start under 1024px

feat: close sidenav on start under 1024px

---

backend/src/main/java/com/example/fintrack/chat/Chat.java

fix: chat optimalization fix

---

front/src/app/core/services/chat/chat.service.ts
front/src/app/shared/controls/chat/chat.component.ts

Update the chat service to return the chat state upon connection and modify the message fetching logic to improve performance and user experience. This includes reversing message order and adjusting parameters for fetching messages.

fix: enhance chat service to return chat state and improve message fetching

---

front/src/app/core/models/chat/last-read-message.model.ts
front/src/app/core/models/chat/socket-requests.model.ts
front/src/app/core/services/chat/chat.service.ts
front/src/app/features/friends/components/chat-list/chat-list.component.html
front/src/app/features/friends/components/chat-list/chat-list.component.scss
front/src/app/features/friends/components/chat-list/chat-list.component.spec.ts
front/src/app/features/friends/components/chat-list/chat-list.component.ts
front/src/app/features/friends/constants/empty-friends-state.const.ts
front/src/app/features/friends/models/friends-state.model.ts
front/src/app/features/friends/pages/friends/friends.component.html
front/src/app/features/friends/pages/friends/friends.component.scss
front/src/app/features/friends/pages/friends/friends.component.ts
front/src/app/features/friends/store/friends-state.store.ts
front/src/app/shared/components/avatar/avatar.component.html
front/src/app/shared/controls/chat/chat.component.ts

* separate chat-list component
* support null values for lastReadMessage
* fix loading chat-list loading state
* send userId in stomp methods
* streamline avatar rendering

refactor:  some chat refactor and some fixes

---

backend/src/main/java/com/example/fintrack/chat/ChatService.java
backend/src/main/java/com/example/fintrack/friend/FriendRepository.java
backend/src/main/java/com/example/fintrack/friend/FriendService.java
backend/src/main/java/com/example/fintrack/friend/FriendStatus.java

Added private readonly chat
